server:
  http_listen_port: 3200

distributor:
  receivers:
    jaeger:
      protocols:
        thrift_http:
        grpc:
        thrift_binary:
        thrift_compact:
    zipkin:
    otlp:
      protocols:
        http:
        grpc:
    opencensus:

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m

compactor:
  compaction:
    compaction_window: 24h
    max_block_bytes: 100_000_000
    block_retention: 24h
    compacted_block_retention: 10m
    flush_size_bytes: 5242880

storage:
  trace:
    backend: s3
    block:
      bloom_filter_false_positive: .05
      index_downsample_bytes: 1000
      encoding: zstd
    wal:
      path: /tmp/tempo/wal
      encoding: snappy
    s3:
      bucket: tempo
      endpoint: minio:9000
      access_key: tempo
      secret_key: Y1IVULzWgwyuiFXamMf9RlXyjKwvVXNF
      insecure: true
    pool:
      max_workers: 100
      queue_depth: 10000
